### ISSUE TITLE
[cocoa] In tests, Shell sometimes doesn't activate

### ISSUE THREAD

**Issue by SyntevoAlex** [eclipse-platform/eclipse.platform.swt#724]
For example, see `test_setFocus_withVisibleAndInvisibleChild` failures:
https://github.com/eclipse-platform/eclipse.platform.swt/runs/14613072507
https://github.com/eclipse-platform/eclipse.platform.swt/runs/14690913997
https://github.com/eclipse-platform/eclipse.platform.swt/runs/14287265191
https://github.com/eclipse-platform/eclipse.platform.swt/runs/14286393799

Also see `test_Issue450_NoShellActivateOnSetFocus` failures:
https://download.eclipse.org/eclipse/downloads/drops4/I20230703-1800/testresults/html/org.eclipse.swt.tests_ep429I-unit-mac64-java17_macosx.cocoa.x86_64_17.html
https://download.eclipse.org/eclipse/downloads/drops4/I20230703-1800/testresults/html/org.eclipse.swt.tests_ep429I-unit-macM1-java17_macosx.cocoa.aarch64_17.html

Also see #721 where timeout was increased.

**Comment by SyntevoAlex** [comment]
Turns out, on macOS, no amount of waiting helps.

Here it can be seen that all tests may fail even after waiting 30 sec:
https://github.com/eclipse-platform/eclipse.platform.swt/runs/14789121538

I noticed the following:
* Sometimes tests succeed
* Sometimes they fail, and all of them seem to fail together.

It seems that when a problem occurs, entire testing session is affected.

**Comment by HeikoKlare** [comment]
Are you sure that this is an issue of the shell not becoming active or only of a missing `Activate` event? I'm just asking because https://github.com/eclipse-platform/eclipse.platform.swt/pull/725 replaced waiting for a shell by becoming the active one of the `Display` by waiting for the SWT event for activation.

**Comment by sratz** [comment]
We've also had issues with `SWT.Activate` not firing on cocoa.

Waiting for `SWT.Show` instead fixed the problem.

**Comment by HeikoKlare** [comment]
Thanks for the hint!

I can easily apply the fix to make the pre-existing focus tests running again, as they did not depend on the `Activate` event before. I am, however, unsure about the regression test for issue #450, i.e., I am unsure whether that test actually depends on awaiting that specific `Activate` event or if replacing it by waiting for `Show` would also be valid.

**Comment by HeikoKlare** [comment]
@SyntevoAlex since you replaced my fix from https://github.com/eclipse-platform/eclipse.platform.swt/pull/721: are you sure that it did not fix the issue with failing tests added by https://github.com/eclipse-platform/eclipse.platform.swt/pull/617? Otherwise I would propose to rollback the changes at least for those tests.

**Comment by SyntevoAlex** [comment]
I will try to figure it tomorrow. I think that both your and my approach fail, because for some reason sometimes Shell simply doesn't activate on macOS.

**Comment by SyntevoAlex** [comment]
Hooray! It wasn't easy, but I think I managed to reproduce exactly the problem in tests, see #731.

I think I can also explain why tests randomly succeed or fail, and my previous observation where either all tests fail or all tests succeed. I think that on tester machine, some other app (or maybe system notification such as "Install updates") pop up during tests.

**Comment by SyntevoAlex** [comment]
This should be fixed by #732.

**Comment by SyntevoAlex** [comment]
> Are you sure that this is an issue of the shell not becoming active or only of a missing Activate event?

It actually doesn't become active, ever. So increasing timeouts wouldn't help.

**Comment by SyntevoAlex** [comment]
> Waiting for SWT.Show instead fixed the problem.

The shell does show, just on background. So if you only wanted to wait for it to show, then `SWT.Show` (or `SWT.Paint`) is good enough approach.

**Comment by HeikoKlare** [comment]
Thanks @SyntevoAlex! Great that you found the reasons and a fix for the random fails on MacOS. Your explanation sounds reasonable considering that in case there are shell-activation-related test failures, they affect most if not all of the executed tests.

If I understand correctly, one thing that might still happen with your fix is that between forcing shell activation
https://github.com/eclipse-platform/eclipse.platform.swt/blob/3ae51898d0a715c86edc8456f88e865d08bf0b2f/tests/org.eclipse.swt.tests/JUnit%20Tests/org/eclipse/swt/tests/junit/SwtTestUtil.java#L406 and the execution of the triggering action
https://github.com/eclipse-platform/eclipse.platform.swt/blob/3ae51898d0a715c86edc8456f88e865d08bf0b2f/tests/org.eclipse.swt.tests/JUnit%20Tests/org/eclipse/swt/tests/junit/SwtTestUtil.java#L409
an event might still occur that activates another shell. This situation would require very specific timing behavior which I would expect to occur very seldom, still we should be aware that it might be the case and in case a seldom failure occurs have at look at that place in code.

I have provided a small follow-up PR that improves assertions in case a failure in this area occurs again and fixes some introduced warnings: #733 

I could imagine that with the recent test utility fix it may also be possible to remove this workaround:
https://github.com/eclipse-platform/eclipse.platform.swt/blob/3ae51898d0a715c86edc8456f88e865d08bf0b2f/tests/org.eclipse.swt.tests/JUnit%20Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_Shell.java#L961-L971

**Comment by SyntevoAlex** [comment]
> an event might still occur that activates another shell

Yes, this is always possible, on any platform and in any test. No matter when we check and what we do, activation can still be stolen in between. That should be very rare though.

> and fixes some introduced warnings

Thanks

> may also be possible to remove this workaround

Probably, but I wasn't sure if it's the same problem or not. `forceActive()` doesn't really fit well in `waitXXX` method and I'm not sure it will stay there. Maybe another problem will be found and I'll have to change method again.

**Comment by SyntevoAlex** [comment]
Alas, there is at least one more problem, it seems.

https://github.com/eclipse-platform/eclipse.platform.swt/actions/runs/5508863388/jobs/10041120000
Here, macOS focus-related tests fail once again, with `Shell did not activate, Shell=<null> is active`

**Comment by SyntevoAlex** [comment]
Curiously, `Test_org_eclipse_swt_widgets_Shell.test_Issue450_NoShellActivateOnSetFocus` does not fail.
